name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake build-essential
    
    - name: Build Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Compile
      run: g++ -std=c++11 -o main 1.cpp -lgtest -lgtest_main -pthread
    
    - name: Run tests
      run: ./main test